export const photos = [
  {
    src: "../static/photos/Ichiban/Exterior/20211201_195858.jpg",
    width: 6,
    height: 3,
    title: "Outside view",
  },
  {
    src: "../static/photos/Ichiban/Exterior/20211201_200142.jpg",
    width: 6,
    height: 3,
    title: "Outside view (side)",
  },
  {
    src: "../static/photos/Ichiban/Exterior/20210702_205305.jpg",
    width: 6,
    height: 3,
    title: "Parking Lot",
  },
  {
    src: "../static/photos/Ichiban/Exterior/20210810_213326.jpg",
    width: 6,
    height: 3,
    title: "Patio",
  },
  {
    src: "../static/photos/Ichiban/Exterior/20210810_211417.jpg",
    width: 3,
    height: 4,
    title: "Patio",
  },
  {
    src: "../static/photos/Ichiban/Exterior/20211206_183533.jpg",
    width: 6,
    height: 3,
    title: "Patio",
  },
  {
    src: "../static/photos/Ichiban/Exterior/20210810_213546.jpg",
    width: 6,
    height: 3,
    title: "Patio",
  },
  {
    src: "../static/photos/Ichiban/Interior/20210728_114508.jpg",
    width: 6,
    height: 3,
    title: "Inside the restaurant",
  },
  {
    src: "../static/photos/Ichiban/Interior/20210814_200912.jpg",
    width: 6,
    height: 3,
    title: "Inside the restaurant",
  },
  {
    src: "../static/photos/Ichiban/Interior/20210814_200929.jpg",
    width: 6,
    height: 3,
    title: "Inside the restaurant",
  },
  {
    src: "../static/photos/Ichiban/Interior/20210814_201001.jpg",
    width: 6,
    height: 3,
    title: "Inside the restaurant",
  },
  {
    src: "../static/photos/Ichiban/Interior/20210814_201031.jpg",
    width: 6,
    height: 3,
    title: "Inside the restaurant",
  },
  {
    src: "../static/photos/Ichiban/Interior/20210814_201135.jpg",
    width: 6,
    height: 3,
    title: "Inside the restaurant",
  },
  {
    src: "../static/photos/Ichiban/Interior/20210814_201446.jpg",
    width: 6,
    height: 3,
    title: "Inside the restaurant",
  },

  {
    src: "../static/photos/Yelp/Yelp-BrianaP.jpg",
    width: 1,
    height: 1,
    title: "Photo by Briana P. (Yelp)",
  },
  {
    src: "../static/photos/Yelp/Yelp-HoganK.jpg",
    width: 1,
    height: 1,
    title: "Photo by Hogan K (Yelp)",
  },
  {
    src: "../static/photos/Yelp/Yelp-JackH.jpg",
    width: 1,
    height: 1,
    title: "Photo by Jack H (Yelp)",
  },
  {
    src: "../static/photos/Yelp/Yelp-RalphS-MangoManiaRoll.jpg",
    width: 4,
    height: 3,
    title: "Photo by Ralph S. (Yelp)",
  },
  {
    src: "../static/photos/Yelp/Yelp-BenD.jpg",
    width: 3,
    height: 4,
    title: "Photo by Ben D. (Yelp)",
  },
  {
    src: "../static/photos/Yelp/Yelp-ScottB.jpg",
    width: 1,
    height: 1,
    title: "Photo by Scott B. (Yelp)",
  },
  {
    src: "../static/photos/Yelp/Yelp-RudyP.jpg",
    width: 3,
    height: 4,
    title: "Photo by Rudy P. (Yelp)",
  },
  {
    src: "../static/photos/Facebook/FB-LoniC(1).jpg",
    width: 3,
    height: 4,
    title: "Photo by Loni C. (Facebook)",
  },
  {
    src: "../static/photos/Facebook/FB-LoniC(2).jpg",
    width: 3,
    height: 4,
    title: "Photo by Loni C. (Facebook)",
  },
  {
    src: "../static/photos/Facebook/FB-LoniC(3).jpg",
    width: 3,
    height: 4,
    title: "Photo by Loni C. (Facebook)",
  },
  {
    src: "../static/photos/Facebook/FB-LoniC(4).jpg",
    width: 3,
    height: 4,
    title: "Photo by Loni C. (Facebook)",
  },
  {
    src: "../static/photos/Facebook/FB-LoniC(5).jpg",
    width: 3,
    height: 4,
    title: "Photo by Loni C. (Facebook)",
  },
  {
    src: "../static/photos/Facebook/FB-LoniC(6).jpg",
    width: 3,
    height: 4,
    title: "Photo by Loni C. (Facebook)",
  },
  {
    src: "../static/photos/Facebook/FB-LoniC(7).jpg",
    width: 3,
    height: 4,
    title: "Photo by Loni C. (Facebook)",
  },
  {
    src: "../static/photos/Facebook/FB-LoniC(8).jpg",
    width: 3,
    height: 4,
    title: "Photo by Loni C. (Facebook)",
  },
];
